# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30801863b7e488586b81332aa6f09062fbacbdc196496e208d4e2f62997610f8d899212165c4e35d9061a14e57e238024aa138ecadb26fd4cea579d33bca1fa3

test:
  secret_key_base: 1739a6008d29d22ddd643b58a693eb6167012dbd5431b2d313259cdfa50420f19a5fe3d8aea4c55895e464605d2db480330e920cec763caa78715095365f4442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
